"""
Sessions router module for TachyonAI.
This module provides endpoints for managing user sessions, including creation, retrieval, and pool generation.
"""
from fastapi import APIRouter, Depends, HTTPException, status, Query
from typing import List, Dict, Optional
from sqlalchemy.orm import Session
import traceback
import logging
from datetime import datetime

from ..database import get_db
from ..models import User, Session as SessionModel, Round, Image
from .. import schemas
from ..auth import get_current_user
from ..schemas import SessionResponse
from ..genetic_pool import generate_pool_with_genetic_algorithm, get_random_pool
from ..embedding import find_nearest_image
from ..pool_image_item import PoolImageItem

# Initialize router and logger
router = APIRouter()
logger = logging.getLogger(__name__)


# Helper functions
def get_last_completed_session(db: Session, user_id: int) -> Optional[SessionModel]:
    """
    Get the last completed session for a user.

    Args:
        db: Database session
        user_id: User ID

    Returns:
        Last completed session or None if there isn't any
    """
    return db.query(SessionModel).filter(
        SessionModel.user_id == user_id,
        SessionModel.status == schemas.SessionStatusEnum.COMPLETED
    ).order_by(SessionModel.ended_at.desc()).first()


# Session endpoints
@router.post("/sessions", response_model=schemas.SessionCreateResponse, status_code=status.HTTP_200_OK)
async def create_session(
    current_user: User = Depends(get_current_user), db: Session = Depends(get_db)
):
    """
    Check user session status and return appropriate information.

    Logic:
    1. Check if any session exists for the user - if not, create a new one with a random pool
    2. Check if an active session exists - if yes, return information about it
    3. Check if a PENDING session exists - if yes, activate it
    4. Check if a completed session exists - if yes, create a new one with a pool generated by the quasi-genetic algorithm

    Args:
        current_user: Current authenticated user
        db: Database session

    Returns:
        Session creation response with session status and statistics

    Raises:
        HTTPException: If there's an error creating or retrieving the session
    """
    try:
        # Check if any session exists for the user
        any_session = db.query(SessionModel).filter(
            SessionModel.user_id == current_user.id
        ).first()

        # 1. If no session exists, create a new one with a random pool
        if not any_session:
            logger.info(f"No session found for user {current_user.id}, creating new one with random pool")
            pos_pool_json, neg_pool_json = get_random_pool(db, 6)

            # Safely validate JSON fields
            try:
                if not pos_pool_json or not isinstance(pos_pool_json, list):
                    raise ValueError("Invalid pos_pool_json format")

                if not neg_pool_json or not isinstance(neg_pool_json, list):
                    raise ValueError("Invalid neg_pool_json format")

                # Check if images have required fields
                for pool_name, pool in [("positive", pos_pool_json), ("negative", neg_pool_json)]:
                    for i, item in enumerate(pool):
                        if not isinstance(item, dict):
                            raise ValueError(f"Image {i} in {pool_name} pool is not a dictionary")

                        if "id" not in item:
                            raise ValueError(f"Image {i} in {pool_name} pool is missing 'id' field")

                logger.info(f"JSON fields for new session are valid")

                new_session = SessionModel(
                    user_id=current_user.id,
                    status=schemas.SessionStatusEnum.ACTIVE,
                    pos_pool_json=pos_pool_json,
                    neg_pool_json=neg_pool_json,
                    session_profit_factor=1.0,
                    remaining_pairs=6,
                    started_at=datetime.utcnow()
                )
                db.add(new_session)
                db.commit()
                db.refresh(new_session)

                # Return information about the new session
                return schemas.SessionCreateResponse(
                    session_exists=True,
                    session_status=schemas.SessionStatusEnum.ACTIVE,
                    session_id=new_session.id,
                    has_unfinished_round=False,
                    unfinished_round_id=None,
                    session_stats={
                        "success_count": 0,
                        "failure_count": 0,
                        "success_rate": 0,
                        "profit_factor": 1.0,
                        "remaining_pairs": new_session.remaining_pairs
                    }
                )

            except ValueError as e:
                logger.error(f"Error validating JSON fields for new session: {str(e)}")
                raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"Session data validation error: {str(e)}")

        # 2. Check if an active session exists
        active_session = db.query(SessionModel).filter(
            SessionModel.user_id == current_user.id,
            SessionModel.status == schemas.SessionStatusEnum.ACTIVE
        ).first()

        if active_session:
            logger.info(f"Found active session {active_session.id} for user {current_user.id}")

            # Check if there are any unfinished rounds
            unfinished_round = db.query(Round).filter(
                Round.session_id == active_session.id,
                Round.result == None
            ).order_by(Round.id.desc()).first()

            # Calculate session statistics
            pos_pool_json = active_session.pos_pool_json
            neg_pool_json = active_session.neg_pool_json

            # Guard against None values
            if pos_pool_json is None:
                pos_pool_json = []
            if neg_pool_json is None:
                neg_pool_json = []

            logger.info(f"Retrieved active session {active_session.id}")
            logger.info(f"Positive pool state: {len(pos_pool_json)} items")
            logger.info(f"Negative pool state: {len(neg_pool_json)} items")

            success_count = db.query(Round).filter(
                Round.session_id == active_session.id, Round.result == "SUCCESS"
            ).count()

            failure_count = db.query(Round).filter(
                Round.session_id == active_session.id, Round.result == "FAILURE"
            ).count()

            session_stats = {
                "success_count": success_count,
                "failure_count": failure_count,
                "success_rate": success_count / (success_count + failure_count) * 100 if (success_count + failure_count) > 0 else 0,
                "profit_factor": active_session.session_profit_factor,
                "remaining_pairs": active_session.remaining_pairs
            }

            return schemas.SessionCreateResponse(
                session_exists=True,
                session_status="ACTIVE",
                session_id=active_session.id,
                has_unfinished_round=unfinished_round is not None,
                unfinished_round_id=unfinished_round.id if unfinished_round else None,
                session_stats=session_stats
            )

        # 3. Check if a PENDING session exists
        pending_session = db.query(SessionModel).filter(
            SessionModel.user_id == current_user.id,
            SessionModel.status == "PENDING"
        ).first()

        if pending_session:
            logger.info(f"Found PENDING session {pending_session.id} for user {current_user.id}, activating it")

            # Safely validate JSON fields
            try:
                if not pending_session.pos_pool_json or not isinstance(pending_session.pos_pool_json, list):
                    raise ValueError("Invalid pos_pool_json format")

                if not pending_session.neg_pool_json or not isinstance(pending_session.neg_pool_json, list):
                    raise ValueError("Invalid neg_pool_json format")

                # Check if images have required fields
                for pool_name, pool in [("positive", pending_session.pos_pool_json), ("negative", pending_session.neg_pool_json)]:
                    for i, item in enumerate(pool):
                        if not isinstance(item, dict):
                            raise ValueError(f"Image {i} in {pool_name} pool is not a dictionary")

                        if "id" not in item:
                            raise ValueError(f"Image {i} in {pool_name} pool is missing 'id' field")

                logger.info(f"JSON fields for PENDING session {pending_session.id} are valid")

                session = pending_session
                session.status = schemas.SessionStatusEnum.ACTIVE
                session.started_at = datetime.utcnow()
                session.session_profit_factor = 1.0

                # Check the number of pairs in pools
                pos_count = len([item for item in session.pos_pool_json if item.get("failures", 0) == 0])
                neg_count = len([item for item in session.neg_pool_json if item.get("failures", 0) == 0])

                if pos_count < 1 or neg_count < 1:
                    logger.warning(f"Too few available pairs in session {session.id}: positive={pos_count}, negative={neg_count}")
                    raise ValueError("Too few available pairs in pools")

                session.remaining_pairs = min(pos_count, neg_count)

                db.commit()
                db.refresh(session)

                return schemas.SessionCreateResponse(
                    session_exists=True,
                    session_status=schemas.SessionStatusEnum.ACTIVE,
                    session_id=session.id,
                    has_unfinished_round=False,
                    unfinished_round_id=None,
                    session_stats={
                        "success_count": 0,
                        "failure_count": 0,
                        "success_rate": 0,
                        "profit_factor": session.session_profit_factor,
                        "remaining_pairs": session.remaining_pairs
                    }
                )

            except ValueError as e:
                logger.error(f"Error validating JSON fields for PENDING session: {str(e)}")
                # If pools are invalid, generate a new pool
                logger.info(f"Generating new pool for session {pending_session.id}")
                pos_pool_json, neg_pool_json = get_random_pool(db, 6)
                pending_session.pos_pool_json = pos_pool_json
                pending_session.neg_pool_json = neg_pool_json
                pending_session.remaining_pairs = 6

                pending_session.status = schemas.SessionStatusEnum.ACTIVE
                pending_session.started_at = datetime.utcnow()
                pending_session.session_profit_factor = 1.0

                db.commit()
                db.refresh(pending_session)
                return schemas.SessionCreateResponse(
                    session_exists=True,
                    session_status=schemas.SessionStatusEnum.ACTIVE,
                    session_id=pending_session.id,
                    has_unfinished_round=False,
                    unfinished_round_id=None,
                    session_stats={
                        "success_count": 0,
                        "failure_count": 0,
                        "success_rate": 0,
                        "profit_factor": pending_session.session_profit_factor,
                        "remaining_pairs": pending_session.remaining_pairs
                    }
                )

        # 4. If no active or pending session exists, but there is a completed one, create a new one with a pool generated by the algorithm
        completed_session = get_last_completed_session(db, current_user.id)

        if completed_session:
            logger.info(f"Found completed session {completed_session.id}, generating new pool with quasi-genetic algorithm")
            pos_pool_json, neg_pool_json = generate_pool_with_genetic_algorithm(completed_session, db)

            # Additional protection against invalid JSON data
            if not pos_pool_json or not neg_pool_json:
                logger.warning("Image pools are empty, using empty lists")
                pos_pool_json = []
                neg_pool_json = []

            new_session = SessionModel(
                user_id=current_user.id,
                status=schemas.SessionStatusEnum.ACTIVE,
                pos_pool_json=pos_pool_json,
                neg_pool_json=neg_pool_json,
                session_profit_factor=1.0,
                remaining_pairs=6,
                started_at=datetime.utcnow()
            )
            db.add(new_session)
            db.commit()
            db.refresh(new_session)

            # Return information about the new session
            return schemas.SessionCreateResponse(
                session_exists=True,
                session_status=schemas.SessionStatusEnum.ACTIVE,
                session_id=new_session.id,
                has_unfinished_round=False,
                unfinished_round_id=None,
                session_stats={
                    "success_count": 0,
                    "failure_count": 0,
                    "success_rate": 0,
                    "profit_factor": 1.0,
                    "remaining_pairs": new_session.remaining_pairs
                }
            )

        # This case should never occur, but we add it for safety
        logger.error(f"Unexpected state: user {current_user.id} has a session, but it's neither active, pending, nor completed")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Unexpected session state")

    except Exception as e:
        logger.error(f"Error checking/creating session: {str(e)}")
        logger.error(traceback.format_exc())
        db.rollback()
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))


@router.post("/sessions/resume/{session_id}", response_model=schemas.Session)
async def resume_session(
    session_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Resume an existing session.

    Args:
        session_id: ID of the session to resume
        current_user: Current authenticated user
        db: Database session

    Returns:
        The resumed session

    Raises:
        HTTPException: If the session doesn't exist, can't be resumed, or there's an error during resumption
    """
    try:
        # Get the session and check if it exists
        session = db.query(SessionModel).filter(
            SessionModel.id == session_id,
            SessionModel.user_id == current_user.id
        ).first()

        if not session:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Session not found")

        # Check if the session has ACTIVE status
        if session.status == schemas.SessionStatusEnum.ACTIVE:
            return session

        # If the session has PENDING status, activate it
        if session.status == schemas.SessionStatusEnum.PENDING:
            logger.info(f"Activating PENDING session {session.id} for user {current_user.id}")

            # Safely validate JSON fields
            try:
                if not session.pos_pool_json or not isinstance(session.pos_pool_json, list):
                    logger.warning(f"Invalid pos_pool_json format in session {session.id}")
                    raise ValueError("Invalid pos_pool_json format")

                if not session.neg_pool_json or not isinstance(session.neg_pool_json, list):
                    logger.warning(f"Invalid neg_pool_json format in session {session.id}")
                    raise ValueError("Invalid neg_pool_json format")

                # Check if images have required fields
                for pool_name, pool in [("positive", session.pos_pool_json), ("negative", session.neg_pool_json)]:
                    for i, item in enumerate(pool):
                        if not isinstance(item, dict):
                            logger.error(f"Image {i} in {pool_name} pool is not a dictionary: {type(item)}")
                        if "id" not in item:
                            logger.error(f"Image {i} in {pool_name} pool is missing 'id' field")

                logger.info(f"JSON fields in session {session.id} are properly formatted")

                session.status = schemas.SessionStatusEnum.ACTIVE
                session.started_at = datetime.utcnow()
                session.session_profit_factor = 1.0

                # Check the number of pairs in pools
                pos_count = len([item for item in session.pos_pool_json if item.get("failures", 0) == 0])
                neg_count = len([item for item in session.neg_pool_json if item.get("failures", 0) == 0])

                if pos_count < 1 or neg_count < 1:
                    logger.warning(f"Too few available pairs in session {session.id}: positive={pos_count}, negative={neg_count}")
                    raise ValueError("Too few available pairs in pools")

                session.remaining_pairs = min(pos_count, neg_count)

                db.commit()
                db.refresh(session)
                return session

            except ValueError as e:
                logger.error(f"Error validating JSON fields in session {session.id}: {str(e)}")
                # If pools are invalid, generate a new pool
                logger.info(f"Generating new pool for session {session.id}")
                pos_pool_json, neg_pool_json = get_random_pool(db, 6)
                session.pos_pool_json = pos_pool_json
                session.neg_pool_json = neg_pool_json
                session.remaining_pairs = 6

                session.status = schemas.SessionStatusEnum.ACTIVE
                session.started_at = datetime.utcnow()
                session.session_profit_factor = 1.0

                db.commit()
                db.refresh(session)
                return session

        # If the session has COMPLETED status, return an error
        if session.status == schemas.SessionStatusEnum.COMPLETED:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Cannot resume a completed session")

        # Just in case the status is unknown
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Cannot resume a session with status {session.status}")

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error resuming session: {str(e)}")
        logger.error(traceback.format_exc())
        db.rollback()
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))


@router.get("/sessions/{session_id}", response_model=schemas.SessionResponse)
async def get_session(
    session_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Get details of a session by ID.

    Args:
        session_id: ID of the session to retrieve
        current_user: Current authenticated user
        db: Database session

    Returns:
        Session details

    Raises:
        HTTPException: If the session doesn't exist or the user doesn't have access to it
    """
    session = db.query(SessionModel).filter(SessionModel.id == session_id).first()
    if not session:
        logger.warning(f"Session {session_id} not found")
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Session not found")
    if session.user_id != current_user.id:
        logger.warning(f"Access denied to session {session_id} for user {current_user.id}")
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied to this session")

    # Ensure JSON fields are properly formatted
    if isinstance(session.pos_pool_json, str):
        try:
            import json
            session.pos_pool_json = json.loads(session.pos_pool_json)
        except json.JSONDecodeError:
            session.pos_pool_json = []

    if isinstance(session.neg_pool_json, str):
        try:
            import json
            session.neg_pool_json = json.loads(session.neg_pool_json)
        except json.JSONDecodeError:
            session.neg_pool_json = []

    return session


@router.get("/sessions/{session_id}/summary", response_model=schemas.SessionSummary)
async def get_session_summary(
    session_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Get a summary of a session by ID.

    Args:
        session_id: ID of the session to summarize
        current_user: Current authenticated user
        db: Database session

    Returns:
        Session summary including statistics and rankings

    Raises:
        HTTPException: If the session doesn't exist, the user doesn't have access to it, or there's an error generating the summary
    """
    try:
        session = db.query(SessionModel).filter(SessionModel.id == session_id).first()
        if not session or session.user_id != current_user.id:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND if not session else status.HTTP_403_FORBIDDEN,
                detail="Session not found or access denied"
            )

        rounds = db.query(Round).filter(Round.session_id == session_id).all()
        success_count = sum(1 for r in rounds if r.result == schemas.RoundResultEnum.SUCCESS)
        failure_count = sum(1 for r in rounds if r.result == schemas.RoundResultEnum.FAILURE)

        # Handle both string and dictionary JSON fields
        pos_pool_json = session.pos_pool_json or []
        neg_pool_json = session.neg_pool_json or []

        # Convert string JSON to dictionary if needed
        import json
        if isinstance(pos_pool_json, str):
            try:
                pos_pool_json = json.loads(pos_pool_json)
            except json.JSONDecodeError:
                pos_pool_json = []

        if isinstance(neg_pool_json, str):
            try:
                neg_pool_json = json.loads(neg_pool_json)
            except json.JSONDecodeError:
                neg_pool_json = []

        pos_items = {item["id"]: PoolImageItem.from_dict(item) for item in pos_pool_json}
        neg_items = {item["id"]: PoolImageItem.from_dict(item) for item in neg_pool_json}

        pos_cumulative = {id_: 1.0 for id_ in pos_items}
        neg_cumulative = {id_: 1.0 for id_ in neg_items}

        for r in rounds:
            if r.result == schemas.RoundResultEnum.SUCCESS:
                if r.pos_image_id in pos_cumulative:
                    pos_cumulative[r.pos_image_id] *= (1 + r.profit_fraction)
                if r.neg_image_id in neg_cumulative:
                    neg_cumulative[r.neg_image_id] *= (1 + r.profit_fraction)

        def build_ranking(items: dict[int, PoolImageItem], cumulative: dict[int, float]):
            return sorted([
                {
                    "id": id_,
                    "successes": item.successes,
                    "failures": item.failures,
                    "cumulative_factor": cumulative.get(id_, 1.0),
                    "origin": item.origin,
                    "parent": None  # parent field is no longer used
                }
                for id_, item in items.items()
            ], key=lambda x: x["successes"], reverse=True)

        summary = {
            "id": session.id,
            "status": session.status,
            "started_at": session.started_at,
            "session_profit_factor": session.session_profit_factor,
            "remaining_pairs": session.remaining_pairs,
            "success_count": success_count,
            "failure_count": failure_count,
            "round_count": success_count + failure_count,
            "pos_stimuli": [item.to_dict() for item in pos_items.values()],
            "neg_stimuli": [item.to_dict() for item in neg_items.values()],
            "pos_ranking": build_ranking(pos_items, pos_cumulative),
            "neg_ranking": build_ranking(neg_items, neg_cumulative)
        }

        return summary
    except Exception as e:
        logger.error(f"Error generating session summary: {e}")
        logger.error(traceback.format_exc())
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))


@router.get("/sessions/{session_id}/rounds", response_model=List[schemas.RoundResponse])
async def get_rounds_for_session(
    session_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Get a list of rounds for a session by ID.

    Args:
        session_id: ID of the session to get rounds for
        current_user: Current authenticated user
        db: Database session

    Returns:
        List of rounds for the session

    Raises:
        HTTPException: If the session doesn't exist or the user doesn't have access to it
    """
    session = db.query(SessionModel).filter(SessionModel.id == session_id).first()
    if not session:
        logger.warning(f"Session {session_id} not found")
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Session not found")
    if session.user_id != current_user.id:
        logger.warning(f"Access denied to session {session_id} for user {current_user.id}")
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied to this session")

    rounds = db.query(Round).filter(Round.session_id == session_id).order_by(Round.round_number).all()
    logger.info(f"Retrieved {len(rounds)} rounds for session {session_id}")
    return rounds


@router.get("/sessions/{session_id}/pool-info", response_model=dict)
async def get_pool_info(
    session_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Check session status and return information about PENDING session and pool statistics.

    Args:
        session_id: ID of the session to check
        current_user: Current authenticated user
        db: Database session

    Returns:
        Dictionary containing information about the session and pool statistics

    Raises:
        HTTPException: If there's an error checking the pool status
    """
    try:
        # Check if a PENDING session exists
        pending_session = db.query(SessionModel).filter(
            SessionModel.user_id == current_user.id,
            SessionModel.status == schemas.SessionStatusEnum.PENDING
        ).order_by(SessionModel.id.desc()).first()

        if pending_session:
            logger.info(f"Found PENDING session {pending_session.id} for user {current_user.id}")

            # Check if the session has generated pools
            has_generated_pools = False
            pool_stats = None

            if pending_session.pos_pool_json and pending_session.neg_pool_json:
                try:
                    # Safely validate JSON fields
                    if isinstance(pending_session.pos_pool_json, list) and isinstance(pending_session.neg_pool_json, list):
                        has_generated_pools = True
                        logger.info(f"Session {pending_session.id} has generated pools")

                        # Calculate pool statistics
                        pool_stats = {
                            "pos_pool": {
                                "total": len(pending_session.pos_pool_json),
                                "bought": sum(1 for item in pending_session.pos_pool_json if item.get("origin", "random") == "bought"),
                                "children": sum(1 for item in pending_session.pos_pool_json if item.get("origin", "").startswith("child_of_")),
                                "random": sum(1 for item in pending_session.pos_pool_json if item.get("origin", "random") == "random"),
                                "random_fallback": sum(1 for item in pending_session.pos_pool_json if item.get("origin", "").startswith("random_fallback_for_")),
                                "images": [{
                                    "id": item["id"],
                                    "origin": item.get("origin", "random"),
                                    "successes": item.get("successes", 0),
                                    "failures": item.get("failures", 0)
                                } for item in pending_session.pos_pool_json]
                            },
                            "neg_pool": {
                                "total": len(pending_session.neg_pool_json),
                                "bought": sum(1 for item in pending_session.neg_pool_json if item.get("origin", "random") == "bought"),
                                "children": sum(1 for item in pending_session.neg_pool_json if item.get("origin", "").startswith("child_of_")),
                                "random": sum(1 for item in pending_session.neg_pool_json if item.get("origin", "random") == "random"),
                                "random_fallback": sum(1 for item in pending_session.neg_pool_json if item.get("origin", "").startswith("random_fallback_for_")),
                                "images": [{
                                    "id": item["id"],
                                    "origin": item.get("origin", "random"),
                                    "successes": item.get("successes", 0),
                                    "failures": item.get("failures", 0)
                                } for item in pending_session.neg_pool_json]
                            },
                            "total_images": len(pending_session.pos_pool_json) + len(pending_session.neg_pool_json)
                        }
                except Exception as e:
                    logger.error(f"Error checking JSON fields: {str(e)}")
                    has_generated_pools = False

            return {
                "has_pending_session": True,
                "pending_session_id": pending_session.id,
                "has_generated_pools": has_generated_pools,
                "pool_stats": pool_stats
            }
        else:
            return {
                "has_pending_session": False,
                "pending_session_id": None,
                "has_generated_pools": False,
                "pool_stats": None
            }

    except Exception as e:
        logger.error(f"Error checking pool status: {str(e)}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))


@router.post("/sessions/generate-pending", response_model=schemas.Message)
async def generate_pending_session(
    request: schemas.GenerateNewPoolRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Generate a new session in PENDING state based on a previous session.

    Args:
        request: Request containing the previous session ID
        current_user: Current authenticated user
        db: Database session

    Returns:
        Message indicating the result of the operation

    Raises:
        HTTPException: If the previous session doesn't exist, isn't completed, or there's an error generating the new session
    """
    try:
        logger.info(f"Starting new pool generation for user {current_user.id}")

        previous_session = db.query(SessionModel).filter(
            SessionModel.id == request.previous_session_id,
            SessionModel.user_id == current_user.id
        ).first()

        if not previous_session:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Previous session not found")

        if previous_session.status != schemas.SessionStatusEnum.COMPLETED:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Previous session is not completed")

        try:
            pos_pool_json = previous_session.pos_pool_json or []
            neg_pool_json = previous_session.neg_pool_json or []

            logger.info(f"Successfully parsed positive pool JSON: {len(pos_pool_json)} items")
            logger.info(f"Successfully parsed negative pool JSON: {len(neg_pool_json)} items")
        except Exception as e:
            logger.error(f"Error parsing pool JSON: {str(e)}")
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Error parsing pool JSON")

        try:
            logger.info(f"Starting new pool generation based on session {previous_session.id}")

            new_pos_pool, new_neg_pool = generate_pool_with_genetic_algorithm(previous_session, db)

            # Ensure each item is an instance of PoolImageItem
            new_pos_pool_json = [
                item.to_dict() if isinstance(item, PoolImageItem) else PoolImageItem.from_dict(item).to_dict()
                for item in new_pos_pool
            ]
            new_neg_pool_json = [
                item.to_dict() if isinstance(item, PoolImageItem) else PoolImageItem.from_dict(item).to_dict()
                for item in new_neg_pool
            ]

            logger.info(f"Generated new pool: {len(new_pos_pool_json)} positive, {len(new_neg_pool_json)} negative")
        except Exception as e:
            logger.error(f"Error generating new pool: {str(e)}")
            logger.error(traceback.format_exc())
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Error generating new pool")

        new_session = SessionModel(
            user_id=current_user.id,
            status=schemas.SessionStatusEnum.PENDING,
            pos_pool_json=new_pos_pool_json,
            neg_pool_json=new_neg_pool_json,
            session_profit_factor=1.0,
            remaining_pairs=6
        )

        db.add(new_session)
        db.commit()
        db.refresh(new_session)

        logger.info(f"Created new PENDING session (id={new_session.id}) for user {current_user.id}")

        return schemas.Message(message="Created new PENDING session")

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error generating PENDING session: {str(e)}")
        logger.error(traceback.format_exc())
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))

@router.post("/sessions/{session_id}/trigger-pool-generation", response_model=schemas.Message)
async def trigger_pool_generation(
    session_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Trigger new pool generation for a user after clicking on session summary.

    Args:
        session_id: ID of the session to use as a base for generation
        current_user: Current authenticated user
        db: Database session

    Returns:
        Message indicating the result of the operation

    Raises:
        HTTPException: If the session doesn't exist or there's an error triggering pool generation
    """
    try:
        # Check if the session exists and belongs to the current user
        session = db.query(SessionModel).filter(
            SessionModel.id == session_id,
            SessionModel.user_id == current_user.id
        ).first()

        if not session:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Session not found")

        # Check if a PENDING session already exists
        existing_pending = db.query(SessionModel).filter(
            SessionModel.user_id == current_user.id,
            SessionModel.status == schemas.SessionStatusEnum.PENDING
        ).first()

        if existing_pending:
            logger.info(f"PENDING session already exists (id={existing_pending.id}) for user {current_user.id}")
            return {"message": f"PENDING session already exists (id={existing_pending.id})"}

        # Use the existing generate_pending_session function
        # Prepare a request object as expected by generate_pending_session
        request = schemas.GenerateNewPoolRequest(previous_session_id=session_id)

        # Call the generate_pending_session function
        logger.info(f"Calling generate_pending_session for session {session_id}")
        result = await generate_pending_session(request, current_user, db)

        return {"message": "Started generating new pool"}

    except Exception as e:
        logger.error(f"Error triggering pool generation: {str(e)}")
        logger.error(traceback.format_exc())
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))

@router.get("/sessions/{session_id}/pools", response_model=List[Dict])
async def get_session_pools(
    session_id: int,
    type: schemas.ImageTypeEnum = Query(schemas.ImageTypeEnum.POSITIVE, description="Pool type: POSITIVE or NEGATIVE"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Get the pool of stimuli (positive/negative) for a given session.

    Args:
        session_id: ID of the session to get pools for
        type: Type of pool to retrieve (POSITIVE or NEGATIVE)
        current_user: Current authenticated user
        db: Database session

    Returns:
        List of pool items

    Raises:
        HTTPException: If the pool type is invalid, the session doesn't exist, or the user doesn't have access to it
    """
    # Type is already validated by FastAPI

    # Get the session
    session = db.query(SessionModel).filter(
        SessionModel.id == session_id,
        SessionModel.user_id == current_user.id
    ).first()

    if not session:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Session not found or access denied")

    # Select the appropriate pool
    pool_json = session.pos_pool_json if type == schemas.ImageTypeEnum.POSITIVE else session.neg_pool_json

    # If the pool is empty, return an empty list
    if not pool_json:
        return []

    # Return the pool data
    return pool_json
